### ISSUE TITLE
Friends Page / Friends' Goals

### ISSUE THREAD

**Issue by dayfine** [dayfine/capstone#11]

**Comment by jhsiung91** [comment]
Friends Page
Display all friends
Add friend
Delete friend

Friends' Goals
View Single Friend's Goals

**Comment by jhsiung91** [comment]
friend-delete branch
- Delete friend logic works both in store and db 

friend-searchadd branch
- search and add friend logic works only in db 
- does not work in front end store update after add

friend-goal-display branch
- going to work on the display of friend goals

**Comment by jhsiung91** [comment]
Used this for friends list
https://material-ui-next.com/demos/cards/
